# Decision Trees

We will use the cars dataset from https://archive.ics.uci.edu/ml/datasets/Car+Evaluation

Also we use some code from http://www.shogun-toolbox.org/static/notebook/current/DecisionTrees.html

In [36]:
# class attribute
evaluation = {'unacc' : 1, 'acc' : 2, 'good' : 3, 'vgood' : 4}

# non-class attributes
buying = {'vhigh' : 1, 'high' : 2, 'med' : 3, 'low' : 4}
maint = {'vhigh' : 1, 'high' : 2, 'med' : 3, 'low' : 4}
doors = {'2' : 1, '3' : 2, '4' : 3, '5more' : 4}
persons = {'2' : 1, '4' : 2, 'more' : 3}
lug_boot = {'small' : 1, 'med' : 2, 'big' : 3}
safety = {'low' : 1, 'med' : 2, 'high' : 3}

In [37]:
f = open('car.data', 'r')

X = []
y = []

# read data from file and encode
for line in f:
    words = line.rstrip().split(',')
    words[0] = int(buying[words[0]])
    words[1] = int(maint[words[1]])
    words[2] = int(doors[words[2]])
    words[3] = int(persons[words[3]])
    words[4] = int(lug_boot[words[4]])
    words[5] = int(safety[words[5]])
    words[6] = evaluation[words[6]]
    X.append(words[0:6])
    y.append(int(words[6]))

f.close()

In [38]:
X

[[1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 2],
 [1, 1, 1, 1, 1, 3],
 [1, 1, 1, 1, 2, 1],
 [1, 1, 1, 1, 2, 2],
 [1, 1, 1, 1, 2, 3],
 [1, 1, 1, 1, 3, 1],
 [1, 1, 1, 1, 3, 2],
 [1, 1, 1, 1, 3, 3],
 [1, 1, 1, 2, 1, 1],
 [1, 1, 1, 2, 1, 2],
 [1, 1, 1, 2, 1, 3],
 [1, 1, 1, 2, 2, 1],
 [1, 1, 1, 2, 2, 2],
 [1, 1, 1, 2, 2, 3],
 [1, 1, 1, 2, 3, 1],
 [1, 1, 1, 2, 3, 2],
 [1, 1, 1, 2, 3, 3],
 [1, 1, 1, 3, 1, 1],
 [1, 1, 1, 3, 1, 2],
 [1, 1, 1, 3, 1, 3],
 [1, 1, 1, 3, 2, 1],
 [1, 1, 1, 3, 2, 2],
 [1, 1, 1, 3, 2, 3],
 [1, 1, 1, 3, 3, 1],
 [1, 1, 1, 3, 3, 2],
 [1, 1, 1, 3, 3, 3],
 [1, 1, 2, 1, 1, 1],
 [1, 1, 2, 1, 1, 2],
 [1, 1, 2, 1, 1, 3],
 [1, 1, 2, 1, 2, 1],
 [1, 1, 2, 1, 2, 2],
 [1, 1, 2, 1, 2, 3],
 [1, 1, 2, 1, 3, 1],
 [1, 1, 2, 1, 3, 2],
 [1, 1, 2, 1, 3, 3],
 [1, 1, 2, 2, 1, 1],
 [1, 1, 2, 2, 1, 2],
 [1, 1, 2, 2, 1, 3],
 [1, 1, 2, 2, 2, 1],
 [1, 1, 2, 2, 2, 2],
 [1, 1, 2, 2, 2, 3],
 [1, 1, 2, 2, 3, 1],
 [1, 1, 2, 2, 3, 2],
 [1, 1, 2, 2, 3, 3],
 [1, 1, 2, 3, 1, 1],
 [1, 1, 2, 3, 1, 2],
 [1, 1, 2, 3,

In [39]:
y

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [40]:
import numpy as np
from numpy import random, delete

features = np.array(X)
labels = np.array(y)

# number of test vectors
num_test_vectors = 200;

test_indices = random.randint(features.shape[0], size = num_test_vectors)
test_features = features[test_indices]
test_labels = labels[test_indices]

# remove test vectors from training set
features = delete(features,test_indices,0)
labels = delete(labels,test_indices,0)

## Basic decision tree

### Depth 2

In [42]:
from sklearn.tree import DecisionTreeClassifier

X = features
y = labels

tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [43]:
len(y_pred[y_pred == test_labels]) / len (y_pred)

0.62

### Depth 3

In [45]:
from sklearn.tree import DecisionTreeClassifier

X = features
y = labels

tree_clf = DecisionTreeClassifier(max_depth=3)
tree_clf.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [46]:
len(y_pred[y_pred == test_labels]) / len (y_pred)

0.62

In [47]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bag_clf = BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=50,
    max_samples=20, bootstrap=True, n_jobs=-1
)
bag_clf.fit(X, y)
y_pred = bag_clf.predict(test_features)

y_pred

array([1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1,
       1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1,
       2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2])

In [48]:
len(y_pred[y_pred == test_labels]) / len (y_pred)

0.785

### Random Forest

In [49]:
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier(n_estimators=50,
    max_leaf_nodes=16, n_jobs=-1
)
rnd_clf.fit(X, y)
y_pred2 = rnd_clf.predict(test_features)

y_pred2

array([2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 3, 1, 2, 1,
       1, 4, 3, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 4, 1, 1, 1, 2, 2, 1, 1, 1, 1,
       1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 4,
       2, 1, 3, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 3, 2, 2, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1,
       1, 1, 1, 3, 1, 4, 1, 3, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1,
       2, 2, 1, 1, 2, 2, 2, 1, 4, 1, 1, 1, 1, 2, 1, 2])

In [50]:
len(y_pred2[y_pred2 == test_labels]) / len (y_pred2)

0.94

### Boosting example

In [55]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

ada_clf = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=2), n_estimators=200,
    algorithm="SAMME.R", learning_rate=0.5
)
ada_clf.fit(X, y)
y_pred3 = ada_clf.predict(test_features)

y_pred3

array([3, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 4, 2, 1, 2, 3, 1, 1, 1,
       2, 4, 3, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 4, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 4, 1, 1, 1, 2, 2, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 4,
       1, 1, 3, 1, 1, 2, 2, 1, 3, 1, 1, 1, 1, 1, 2, 2, 3, 2, 2, 1, 1, 2, 2,
       1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1,
       1, 1, 1, 3, 1, 4, 1, 3, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 1, 2, 1,
       3, 2, 1, 1, 2, 4, 2, 1, 4, 1, 2, 1, 1, 2, 1, 2])

In [56]:
len(y_pred3[y_pred3 == test_labels]) / len (y_pred3)

0.9

In [53]:
! pip install pydotplus
from sklearn.tree import export_graphviz
from sklearn import tree
import pydotplus
from IPython.display import Image  

export_graphviz(
    tree_clf,
    out_file='car_tree.dot',
    feature_names=['buying','maint','doors','persons','trunk','safety'],
    class_names=['unacc','acc','good','vgood'],
    rounded=True,
    filled=True
)

#graph = pydotplus.graph_from_dot_data(dot_data) 
#Image(graph.create_png())  

You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [57]:
! pip install pydotplus
from sklearn import tree
import pydotplus

#dot_data = tree.export_graphviz(tree_clf, out_file=None) 
#graph = pydotplus.graph_from_dot_data(dot_data) 
#graph.write_pdf("car_tree.pdf") 

You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


## Detailed breakdown of computing entropy, info gain


In [58]:
# From http://gabrielelanaro.github.io/blog/2016/03/03/decision-trees.html

import numpy as np
x1 = [0, 1, 1, 2, 2, 2]
x2 = [0, 0, 1, 1, 1, 0]
y = np.array([0, 0, 0, 1, 1, 0])

def partition(a):
    return {c: (a==c).nonzero()[0] for c in np.unique(a)}

def entropy(s):
    res = 0
    val, counts = np.unique(s, return_counts=True)
    freqs = counts.astype('float')/len(s)
    for p in freqs:
        if p != 0.0:
            res -= p * np.log2(p)
    return res

def mutual_information(y, x):

    res = entropy(y)
    print ('Initial entropy: ', res)

    # We partition x, according to attribute values x_i
    val, counts = np.unique(x, return_counts=True)
    freqs = counts.astype('float')/len(x)

    # We calculate a weighted average of the entropy
    for p, v in zip(freqs, val):
        print ('Split on ', v, entropy(y[x == v]))
        res -= p * entropy(y[x == v])

    return res

from pprint import pprint

def is_pure(s):
    return len(set(s)) == 1

def recursive_split(x, y):
    # If there could be no split, just return the original set
    if is_pure(y) or len(y) == 0:
        return y

    # We get attribute that gives the highest mutual information
    gain = np.array([mutual_information(y, x_attr) for x_attr in x.T])
    selected_attr = np.argmax(gain)

    # If there's no gain at all, nothing has to be done, just return the original set
    if np.all(gain < 1e-6):
        return y


    # We split using the selected attribute
    sets = partition(x[:, selected_attr])

    res = {}
    for k, v in sets.items():
        y_subset = y.take(v, axis=0)
        x_subset = x.take(v, axis=0)

        res["x_%d = %d" % (selected_attr, k)] = recursive_split(x_subset, y_subset)

    return res

X = np.array([x1, x2]).T
pprint(recursive_split(X, y))

Initial entropy:  0.918295834054
Split on  0 0.0
Split on  1 0.0
Split on  2 0.918295834054
Initial entropy:  0.918295834054
Split on  0 0.0
Split on  1 0.918295834054
Initial entropy:  0.918295834054
Split on  2 0.918295834054
Initial entropy:  0.918295834054
Split on  0 0.0
Split on  1 0.0
{'x_0 = 0': array([0]),
 'x_0 = 1': array([0, 0]),
 'x_0 = 2': {'x_1 = 0': array([0]), 'x_1 = 1': array([1, 1])}}


In [59]:
gain = np.array([mutual_information(y, x_attr) for x_attr in X.T])
gain

Initial entropy:  0.918295834054
Split on  0 0.0
Split on  1 0.0
Split on  2 0.918295834054
Initial entropy:  0.918295834054
Split on  0 0.0
Split on  1 0.918295834054


array([ 0.45914792,  0.45914792])

In [60]:
np.argmax(gain)

0

In [61]:
mutual_information(y, x1)

Initial entropy:  0.918295834054
Split on  0 0.0
Split on  1 0.0
Split on  2 0.918295834054


0.45914791702724478

In [62]:
4/6 * np.log2(4/6) + 2/6 * np.log2(2/6)

-0.91829583405448956